import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {useEffect, useState} from "react";
import NATS from "../clientNats/clientNats";
import Link from "next/link";
import Header from "../partial/header";
import {paginate} from "../mFun";

export default function Home() {
    const [ page , setPage ] = useState(1)
    const [products, setProduct] = useState( [] )
    useEffect( () => {
        (async () => {
        try {
            let {data} = await NATS.getProducts( {where: {'data.active': 'active'}, sort: {'created': -1}, skip: 0, limit: 1000} )
            const d = paginate(data, page)
            if(page <= 1) setProduct( d )
            else setProduct(products => [...products, ...d])
        } catch (e) {
            console.log( e )
        }
        })()
    }, [page] )

    const [scrollTop, setScrollTop] = useState(false)
    useEffect( () => {
        const handleScroll = () => {
            if(document.documentElement.scrollTop > 3000) setScrollTop(true)
            else setScrollTop(false)
            const bottom = (document.documentElement.scrollHeight) - document.documentElement.scrollTop <= document.documentElement.clientHeight + 100;
            if (bottom) setPage( p => p + 1 )
        }
        window.addEventListener( 'scroll', handleScroll );
        return () => window.removeEventListener( 'scroll', handleScroll );
    } );

    const category = [
        {name: 'Áo nam', image: 'https://chatboxfacebook.herokuapp.com/image/ao.png'},
        {name: 'Áo ba lỗ', image: 'https://chatboxfacebook.herokuapp.com/image/ao_ba_lo.jpg'},
        {name: 'Áo blazer áo vest', image: 'https://chatboxfacebook.herokuapp.com/image/ao_blazer_ao_vest.png'},
        {name: 'Áo hoodie', image: 'https://chatboxfacebook.herokuapp.com/image/ao_hoodie_ao_len_va_ao_ni.jpg'},
        {name: 'Áo khoác', image: 'https://chatboxfacebook.herokuapp.com/image/ao_khoac.jpg'},
        {name: 'Cà vạt', image: 'https://chatboxfacebook.herokuapp.com/image/ca_vat_va_no_co.png'},
        {name: 'Đồ bộ', image: 'https://chatboxfacebook.herokuapp.com/image/do_bo.png'},
        {name: 'Đồ hóa trang', image: 'https://chatboxfacebook.herokuapp.com/image/do_hoa_trang.png'},
        {name: 'Đồ lót', image: 'https://chatboxfacebook.herokuapp.com/image/do_lot.jpg'},
        {name: 'Kính mắc', image: 'https://chatboxfacebook.herokuapp.com/image/kinh_mat_nam.png'},
        {name: 'classic', image: 'https://chatboxfacebook.herokuapp.com/image/phong_cach_classic_nam.jpeg'},
        {name: 'Phụ kiện', image: 'https://chatboxfacebook.herokuapp.com/image/phu_kien_nam.png'},
        {name: 'Quần jean', image: 'https://chatboxfacebook.herokuapp.com/image/quan_jean.png'},
        {name: 'Thất lưng', image: 'https://chatboxfacebook.herokuapp.com/image/that_lung_nam.jpg'},
        {name: 'Trang phục ngành', image: 'https://chatboxfacebook.herokuapp.com/image/trang_phuc_nganh_nghe.png'},
        {name: 'Trang sức', image: 'https://chatboxfacebook.herokuapp.com/image/trang_suc_nam.jpg'},
        {name: 'Vớ tắt', image: 'https://chatboxfacebook.herokuapp.com/image/vo_tat.jpg'},
    ]
    return (
        <div className={styles.home}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <div className={styles.container}>
                <div className={styles.category_product}>
                    <div className={styles.title}>Danh Mục Sản phẩm</div>
                    <div className={styles.list_category}>
                        {category.map((e, i) => {
                            const {image, name} = e
                            return (
                                <div key={i} className={styles.item_category}>
                                    <img src={image} alt=""/>
                                    <span>{name}</span>
                                </div>
                            )
                        } )}
                    </div>
                </div>
                <div className={styles.wrapper_bars}>
                    <div className={styles.bars_products}>
                        <div className={styles.title}>Sản Phẩm Hôm Nay</div>
                    </div>
                </div>
                <div className={styles.list_products} >
                    {products?.map( (e, i) => {
                        const {_id, nameProduct, priceDrops, price, percentDrops, imageSmalls} = e
                        return (
                            <Link href={_id} key={i}>
                                <div className={styles.item_product}>
                                    <div className={styles.wrapper_image}>
                                        <img src={imageSmalls[0]} alt="" width={100} height={100}/>
                                    </div>
                                    <div className={styles.info_product}>
                                        <div className={styles.name_product}>{nameProduct}</div>
                                         <div className={styles.price_drops}>{priceDrops}</div>
                                        <div className={styles.price}>{price}</div>
                                        <div className={styles.price}>{percentDrops}</div>
                                    </div>
                                </div>
                            </Link>
                        )
                    } )}
                </div>
                { scrollTop && <div className={styles.scroll_top} onClick={() => window.scrollTo({top: 0, behavior: 'smooth'})}>
                    <i className={'fad fa-angle-up'}/>
                </div> }
            </div>
        </div>
    )
}
